CFLAGS=-std=c99 -pedantic -Wall -O
CXXFLAGS=-static -pedantic -Wall -Weffc++ -Wextra -Wold-style-cast -O
STRIP=strip
CC=gcc
CXX=g++
EXE_EXT=.exe

include Makefile.common

clean:
	del /Q /S $(EXE_NAME) $(OBJECTS)
    