CFLAGS=-std=c99 -pedantic -Wall -O
CXXFLAGS=-static -pedantic -Wall -Weffc++ -Wextra -Wold-style-cast -O
STRIP=i686-w64-mingw32-strip
CC=i686-w64-mingw32-gcc
CXX=i686-w64-mingw32-g++
EXE_EXT=.exe

include Makefile.common
