CFLAGS=-std=c99 -pedantic -Wall -O
CXXFLAGS=-static -pedantic -Wall -Weffc++ -Wextra -Wold-style-cast -O
STRIP=i586-mingw32msvc-strip
CC=i586-mingw32msvc-gcc
CXX=i586-mingw32msvc-g++
EXE_EXT=.exe

include Makefile.common
